image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - init: npm install
    command: npm run start

vscode:
  extensions:
    - https://github.com/freeCodeCamp/freecodecamp-dark-vscode-theme/releases/download/v1.0.0/freecodecamp-dark-vscode-theme-1.0.0.vsix


>vscode
--settings.json
>public
--style.css
> routes
  --api.js
  --fcctesting.js
>tests
  --functional-test.js
> views
  --board.html
  --index.html
  --thread.html

--package.json
--package-lock.json
--models.js
--db-connection.js
serv.js
.env